### ISSUE TITLE
🐛 BUG: Attributes names are removed

### ISSUE THREAD

**Issue by altano** [withastro/prettier-plugin-astro#114]
### Describe the Bug

Attribute names are removed from component usage in .astro files:

Original code:
```
<BaseHead title={title} description={description} permalink={permalink} />
```

Formatted to:
```
<BaseHead {title} {description} {permalink} />
```

Expected:
```
<BaseHead title={title} description={description} permalink={permalink} />
```

This shorter syntax seems to work but there are two problems with it:
1. It isn't documented
2. It doesn't work with TypeScript
![image](https://user-images.githubusercontent.com/1009/150616445-26eecdb2-a21c-402f-b8c3-943fec8ff786.png)

### Steps to Reproduce

See code formatting examples above

**Comment by briannicholas** [comment]
add this to your `.prettierrc` file

`"astroAllowShorthand": false`

**Comment by altano** [comment]
Works for me, thanks!

Give that the shorthand syntax is undocumented and doesn't (can't?) work with TypeScript props, and TypeScript is baked into Astro such that you don't opt-in to it, should longhand props be the default?
