### ISSUE TITLE
🐛 BUG: Formatter not working as expected

### ISSUE THREAD

**Issue by retronav** [withastro/prettier-plugin-astro#115]
### Describe the Bug

The parser is outputting a weird error code that is incomprehensible to me. Also the code on which this error is occurring works fine in the Astro compiler. 

Here's the code on which this is failing:
```astro
<aside>
    {tags && tags.length > 0 && (
      <p>
      <span>Tags:&nbsp;</span>
        {tags.map((tag, i) => (
          <a href={`/tags/${tag}`}><code>#{tag}</code></a>
          <span>{i < tags.length - 1 && ', '}</span>
        ))}
      </p>
    )}
    {categories && categories.length > 0 && (
      <p>
      <span>Categories:&nbsp;</span>
        {categories.map((category, i) => (
          <a href={`/categories/${category}`}><code>{category}</code></a>
          <span>{i < categories.length - 1 && ', '}</span>
        ))}
        </p>
    )}
  </aside>
```

### Steps to Reproduce

1. `npm init astro` using template minimal
2. Put the code in any Astro file
3. Run prettier with the Astro plugin on the file
5. Error! Describe what went wrong (and what was expected instead)...
Outputs a stack trace from which I can't conclude what went wrong. It was expected that the code is formatted correctly.

Here's the stack trace:
```
[error] src/layouts/PostLayout.astro: ParseError: Expected =
[error]     at error (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/utils/error.js:46:15)
[error]     at Parser.error (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/index.js:97:30)
[error]     at Parser.acorn_error (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/index.js:91:10)
[error]     at read_expression (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/read/expression.js:225:12)
[error]     at mustache (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/state/mustache.js:316:54)
[error]     at new Parser (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/index.js:57:15)
[error]     at Object.parse (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/@astrojs+parser@0.22.0/node_modules/@astrojs/parser/dist/parse/index.js:187:18)
[error]     at Object.parse (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/prettier-plugin-astro@0.0.12/node_modules/prettier-plugin-astro/dist/index.js:14:32)
[error]     at Object.parse$d [as parse] (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:12975:19)
[error]     at coreFormat (/home/pranav/Programming/Projects/personal-website/node_modules/.pnpm/prettier@2.5.1/node_modules/prettier/index.js:14525:16)
```

**Comment by BenjaminPrice** [comment]
I am experiencing the same issue.

**Comment by jasikpark** [comment]
What version of astro and prettier-plugin-astro are you using?

**Comment by jdahdah** [comment]
Similar issue here. Perfectly valid jsx is breaking Prettier formatting both in VSCode and the command line. The compiler runs it fine. The simplest example I can think of would be:

**Test.astro:**
```astro
---
const items = [1, 2, 3]
---

<ul>
  {items.map((item) => (
    <li>{item}</li>
  ))}
</ul>
```

Results in this error:

```
src/components/Test.astro
[error] src/components/Test.astro: ParseError: (0 , import__2.default) is not a function
[error]     at error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/utils/error.js:51:15)
[error]     at Parser.error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:102:30)
[error]     at Parser.acorn_error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:96:10)
[error]     at read_expression (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/read/expression.js:230:12)
[error]     at mustache (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/state/mustache.js:321:54)
[error]     at new Parser (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:62:15)
[error]     at Object.parse (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:192:18)
[error]     at Object.parse (/Users/username/Development/foo/node_modules/prettier-plugin-astro/dist/index.js:14:32)
[error]     at Object.parse (/Users/username/Development/foo/node_modules/prettier/index.js:7361:23)
[error]     at coreFormat (/Users/username/Development/foo/node_modules/prettier/index.js:8672:18)
```

astro 1.0.0-beta.12
prettier 2.6.2
prettier-plugin-astro 0.0.12

**Comment by antonyfaris** [comment]
@jdahdah thank you for reporting. The snippet that you posted will run fine with the next version of the plugin.

**Comment by mvolfik** [comment]
@antonyfaris I tried cloning this repository, building it and installing the plugin from there, but it still throws the error - i.e. doesn't seem to be fixed in next version

**Comment by mvolfik** [comment]
Oh, I completely missed that the development happens on a separate branch and that there are literal `next` versions of the plugin. Sorry about that and thanks :)

**Comment by moritzlaube** [comment]
> Similar issue here. Perfectly valid jsx is breaking Prettier formatting both in VSCode and the command line. The compiler runs it fine. The simplest example I can think of would be:
> 
> **Test.astro:**
> 
> ```astro
> ---
> const items = [1, 2, 3]
> ---
> 
> <ul>
>   {items.map((item) => (
>     <li>{item}</li>
>   ))}
> </ul>
> ```
> 
> Results in this error:
> 
> ```
> src/components/Test.astro
> [error] src/components/Test.astro: ParseError: (0 , import__2.default) is not a function
> [error]     at error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/utils/error.js:51:15)
> [error]     at Parser.error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:102:30)
> [error]     at Parser.acorn_error (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:96:10)
> [error]     at read_expression (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/read/expression.js:230:12)
> [error]     at mustache (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/state/mustache.js:321:54)
> [error]     at new Parser (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:62:15)
> [error]     at Object.parse (/Users/username/Development/foo/node_modules/@astrojs/parser/dist/parse/index.js:192:18)
> [error]     at Object.parse (/Users/username/Development/foo/node_modules/prettier-plugin-astro/dist/index.js:14:32)
> [error]     at Object.parse (/Users/username/Development/foo/node_modules/prettier/index.js:7361:23)
> [error]     at coreFormat (/Users/username/Development/foo/node_modules/prettier/index.js:8672:18)
> ```
> 
> astro 1.0.0-beta.12 prettier 2.6.2 prettier-plugin-astro 0.0.12

I am having the exact same issue. Using "^0.1.0-next.5" of the plugin

**Comment by antonyfaris** [comment]
> I am having the exact same issue. Using "^0.1.0-next.5" of the plugin.
> 
> When commenting out the JSX expression (the map function). Everything works fine again.

That's odd. I just tested the snippet above with `0.1.0-next.5` and it works fine.

**Comment by moritzlaube** [comment]
> That's odd. I just tested the snippet above with `0.1.0-next.5` and it works fine.

My bad! I'm truly sorry. I forgot to add the `.prettierrc` with the plugins array pointing to your plugin in my project. Now it works. Sorry for the confusion!

**Comment by antonyfaris** [comment]
> My bad! I'm truly sorry. I forgot to add the `.prettierrc` with the plugins array pointing to your plugin in my project. Now it works. Sorry for the confusion!

No problem! I'm glad it's working for you.
