### ISSUE TITLE
🐛 BUG: Weird formatting

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/prettier-plugin-astro#142]
### Describe the Bug

The prettier plugin is generating weird outputs for code blocks that are a bit longer writing in a single line.

```md
<Image src="https://picsum.photos/200/300" alt="A random image" brightness={0.5} />

<Image 
  src="https://picsum.photos/200/300" 
  alt="A random image" 
  brightness={0.5}
/>

<!-- The prettier plugin is formatting the above two code blocks to the below code block -->

<Image src="https://picsum.photos/200/300" alt="A random image" brightness={0.5}
/>
```

 I am not very familiar with how prettier plugins work but I think this plugin first minifies the code and then starts formatting it. I think that's why the multi-line code block is also getting formatted in the same way.

### Steps to Reproduce

The prettier plugin should break the single-line code block into multiple lines and keep the multi-line code block as it is.

**Comment by jasikpark** [comment]
the babel parser for prettier produces image blocks that are on multiple lines like the second Image instance: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAfKgkgWwIYDmcABAM4BOYAvADogAWMMADqUgPTvMCWYpArjgB0zehBgRS7AEwAGWewDM8usTwAbGLRABBYuTxQAJhBzFu+IqoBG5bgUZQ4pUlWCyhAVgC+xduhooQOxLEkDiMkptRhY2Th4+QRExCSk5BWVZVXC1TW09A2NTc1DsqAjbe0dnV3cvb0D-QODcQhIKajoY1g4uXgFhUXFJGXklFRBcrToCwxMzCzabOwcYJxc3Dx9GzH8QABoQCGYYbmhSZFA8cnIIAHcABWuEC5QNO7wATwvD2zwwADWcBgAGU8Dg4AAZbhOZAAMw0pDgvwMgOBIOY-xhBGQMHI-GRIDgOGscCMRjJkMMBH4bQAYhByPgmNjkCA8PwJAcGDAcOoAOr0bjwUiYsBwEEvYXcABuws+bL4PxAMKR5BgDwMBHw8MRhIAVqQAB4g7HqOAARX44jguvUSMOmPIarZ1jwpPU3OYdlg-O4Rhg9GQAA5ZI7bkj+QZmGzvc44OQZbbDgBHa3wTXHV7s0gAWicZLJ3PIcDT3BLmsIOqQCPthKROG4uPx9bNlvTtpresOMHdfoDQaQ0h7Bm46mxAGFTNWiaRPNz+EiACru161h0gGUErDGBCgsB2E46YwgmCfc12pHebxAA

**Comment by antonyfaris** [comment]
This happens because the line it's reaching the max-width but it's not adding new lines for the attributes which is a bug. It's been handled by the plugin itself, not the babel parser.
