### ISSUE TITLE
📘 DOC: Document the minimum astro version supported per version

### ISSUE THREAD

**Issue by jasikpark** [withastro/prettier-plugin-astro#164]
Currently `prettier-plugin-astro@0.0.12` fails to format for me. Maybe it need to have a minimum supported astro version documented per version?

Is the astro parser as a dependent of this plugin pinned? Or will it interact w/ the astro version you have open? 

the error I was seeing:
```sh
src/pages/nebula/[slug].astro[error] src/pages/nebula/[slug].astro: ParseError: (0 , import__2.default) is not a function
```

`prettier-plugin-astro@0.0.11` formats for me w/o error

**Comment by jasikpark** [comment]
Testing out `prettier-plugin-astro@0.1.0-next.3` results in a full second of parse+format time per file 😬

**Comment by jasikpark** [comment]
Ok, looking in my lockfile, I see that astro is depending on `@astrojs/compiler@0.0.12` vs the prettier plugin using `@astrojs/compiler@0.0.13` when installed as `prettier-plugin-astro@0.1.0-next.3`

**Comment by Princesseuh** [comment]
We are at a point where this shouldn't really be an issue anymore unless Astro's syntax has major changes (which is pretty unlikely and would have plenty of implications) as the compiler has gotten way more stable overtime 👍
