### ISSUE TITLE
🐛 BUG: 0.1.0-next.4 changes HTML attribute quotes depending on `singleQuote` option in Prettier

### ISSUE THREAD

**Issue by davidwarrington** [withastro/prettier-plugin-astro#174]
### Describe the Bug

With the `singleQuote` option set to `true` in `.prettierrc`, HTML attributes are given single quotes rather than double. This is not the default behaviour of Prettier for HTML. The `jsxSingleQuote` attribute appears to be the setting that controls this (within JSX files, unsure about other languages).

`component.astro` before running Prettier:
```html
<h1 class="site-title"></h1>
```

`component.astro` after running Prettier:
```html
<h1 class='site-title'></h1>
```

I've done some digging into the source, and it seems switching line 401 of `printer.ts` from:
```ts
const quote = opts.singleQuote ? "'" : '"';
```

to
```ts
const quote = '"';
```

is enough to handle it, however it's not something I've thoroughly tested, and I've been unable to get the `option-single-quote-true` and `option-single-quote-false` tests re-enabled and working so far.

---

I did also notice here that the (currently disabled) `option-jsx-single-quote-true` and `option-jsx-single-quote` tests aren't testing the right thing. At the moment they're written to check if Prettier will change the quotes inside JSX expressions, whereas when I investigated on a [test repo](https://github.com/davidwarrington/prettier-single-quote-test), the `jsxSingleQuote` option actually controls whether or not attributes on elements in JSX are wrapped in double or single quotes.

---

Another related issue I noticed is that the attribute quotes issues above doesn't apply to templates nested inside JSX/JSX-like expressions, for example with this code, the `class="list"` will be modified, but `class="list-item"` won't be
```html
 <ul class="list">
   {[1, 2, 3].map(value => <li class="list-item">{value}</li>)}
 </ul>
 ```
 
 I've not investigated enough to know if this plugin just doesn't run at all on nested expressions or if the issue is specific to the `singleQuote` rule.

### Steps to Reproduce

Part 1:
1. `npm init astro` using any template and `yarn` to install dependencies
2. `yarn add --dev prettier prettier-plugin-astro@next`
3.  Create `.prettierrc` with the following options:
    ```json
    {
      "singleQuote": true
    }
    ```
4. Run `yarn prettier --write .`
5. Error! The value of the `<html lang="en">` tag in `src/pages/index.astro` will now be `<html lang='en'>`.

Part 2:
1. Add the following before the `</main>` tag in `index.astro`:
    ```html
    <ul class="list">
      {[1, 2, 3].map(value => <li class="list-item">{value}</li>)}
    </ul>
    ```
2. Run `yarn prettier --write .`
3. Error! The value will be changed to:
    ```html
    <ul class='list'>
      {[1, 2, 3].map(value => <li class="list-item">{value}</li>)}
    </ul>
    ```

**Comment by antonyfaris** [comment]
Thank you for opening this issue. You are right! I will take a look into it.

**Comment by mayank99** [comment]
I've noticed some even more weird/opposite behavior.

I'm using `0.1.0-next.4` with the following options:
```
    "jsxSingleQuote": true,
    "singleQuote": true,
```

Anything in JS-land (inside curly braces) gets single quotes, which is fine, but anything outside the curlies remains with double quotes.

On line 16 below, you can see mismatching quotes in the same line.
![line 16 reads: <html dir={content.dir ?? 'ltr'} lang={content.lang ?? 'en-us'} class="initial">](https://user-images.githubusercontent.com/9084735/164799149-800358ba-c55d-46b7-8c26-9bee7c66d2e7.png)

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/prettier-plugin-astro/pull/236
