### ISSUE TITLE
🐛 BUG: Label element split onto next line

### ISSUE THREAD

**Issue by SteveALee** [withastro/prettier-plugin-astro#189]
### Describe the Bug

Some instances of &lt;label&gt; are incorrectly formated with the closing %gt; being placed on a nerw line

```astro
---
---
<label
  >Text:
  <span>ss</span>
</label>
```

### Steps to Reproduce

Astro file as follows and run `npx prettier -w .`as described in the README

```astro
---
---
<label>Text:
  <span>ss</span>
</label>

```

**Comment by Princesseuh** [comment]
The same thing seems to happens inside an HTML file. I think this might be normal Prettier behaviour?

**Comment by antonyfaris** [comment]
> The same thing seems to happens inside an HTML file. I think this might be normal Prettier behaviour?

You can see how Prettier formats this snippet in their [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QPgBU4APGJAHSgAJrUBnAB0yn3vtQHomX8qusuAiAA0ICIxgBLaPWShMAJ0UQA7gAUlCOSkzpVmAJ5yx2RZjABrODADKmALZwAMlKhxkAMz304p81Y2tsxgbgDmyDCKAK5+IHAOuAAmSXBJzixh0ZhhcABiEIoOmDDSUBG60TAQoiAAFjAO6ADqdVLwPGBwttrtUgBu7YbI4Oy1br6KMOrmYcVePnEAVvQktuHocACK0RDwC+i+YsyKkyMNTbWMim4wzVJJMHXIABwADMcqvs3mjCPXcEm-Q8YgAjrt4DMJDoQJh6ABadxpNK1RRwcFSNEzHLzJDeQ5xXwOKSRGKEjbbCEePGLMQwHD3R7PJAAJjp5ik6HCAGEIA5cfF6ABWWrRXyEHA6fFHED9WIASSgqVgtjAN0kAEElbYYIZNgdfABfQ1AA).
