### ISSUE TITLE
🐛 BUG: JSX style comment in Markdown

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/prettier-plugin-astro#201]
### Describe the Bug

Prettier is transforming
`{/*` into `{/\*`
Also, JSX comments aren't taken into account by the AST / Syntax highlighter, still in Markdown.
They just behave as plain text (but that's another issue)

**Comment by Princesseuh** [comment]
Closing as a duplicate of https://github.com/withastro/prettier-plugin-astro/issues/61
