### ISSUE TITLE
🐛 BUG: prettier-plugin-tailwindcss doesn't work in .astro files

### ISSUE THREAD

**Issue by inwardmovement** [withastro/prettier-plugin-astro#202]
### Describe the Bug

[prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) doesn't work in `.astro` files.

### Steps to Reproduce

1. In an Astro project, run `npm i -D prettier prettier-plugin-astro prettier-plugin-tailwindcss`.
2. Add Tailwind classes and save: classes are not reordered according to the [recommended class order](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted).

**Comment by Princesseuh** [comment]
Hey, I made a PR to their plugin to get this working: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/87

Hope we can get it merged!

**Comment by Princesseuh** [comment]
Update on this, the main branch of the Tailwind plugin support Astro nicely, however the Tailwind team would like to find a more consistent way to support different frameworks before releasing. As such, the release of it will be delayed

More information here https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/87#issuecomment-1218432784

**Comment by fandy** [comment]
This is sweet @Princesseuh! Can you post an update when the release is deployed?

**Comment by Princesseuh** [comment]
> This is sweet @Princesseuh! Can you post an update when the release is deployed?

Yep, no worries! I'll post a message here and close this issue when they'll release it. You can also follow their PR here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/90

**Comment by Princesseuh** [comment]
Hi everyone, we are still waiting on the Tailwind team. [Adam recently posted an answer](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1279750502) saying they would take a look in early November

Hope we can get this working soon 🤞

**Comment by Temez1** [comment]
There's a beta version that can be used for now :) See the [comment](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1319130168)

**Comment by limisc** [comment]
It doesn't work with 
"prettier": "3.0.0",
"prettier-plugin-astro": "^0.11.0",
"prettier-plugin-tailwindcss": "^0.4.1",

**Comment by Princesseuh** [comment]
> It doesn't work with 
> "prettier": "3.0.0",
> "prettier-plugin-astro": "^0.11.0",
> "prettier-plugin-tailwindcss": "^0.4.1",

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/186#issuecomment-1650499607
