### ISSUE TITLE
💡 RFC: slots should be self-closing

### ISSUE THREAD

**Issue by inwardmovement** [withastro/prettier-plugin-astro#228]
### Background & Motivation

`slots` in astro components should be self-closing:

`<slot></slot>`  --->  `<slot />`

For now Prettier/prettier-plugin-astro keep transforming `<slot />`  to  `<slot></slot>` which does not mirror `slots` examples from the docs.

### Risks, downsides, and/or tradeoffs
Opts out of default prettier behavior

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Totally agree, we'll get this done!
