### ISSUE TITLE
🐛 BUG: Prettier hangs when importing from 'astro/components'

### ISSUE THREAD

**Issue by karlschwaier** [withastro/prettier-plugin-astro#232]
### Describe the Bug

The formatting process hangs without any error message if I import Code or Debug from 'astro/components'.

code.astro:
```astro
---
import { Code } from 'astro/components';
---
<h1>Test
</h1>
```

But it works if I import Markdown.

markdown.astro:
```astro
---
import { Markdown } from 'astro/components';
---
<h1>Test
</h1>
```

### Steps to Reproduce

1. `npx prettier code.astro`
2. Terminal hangs
3. `npx prettier markdown.astro`
4. Terminal shows you correctly formatted code

I am using

- astro 1.0.0-beta.69
- prettier 2.7.1
- prettier-plugin-astro 0.1.1
- node 16.15.1
- npm 8.11.0

**Comment by JulianCataldo** [comment]
Same here.


```
---
import { Code } from 'astro/components';  
---

```

'astro' string is what's make prettier break

**Comment by Princesseuh** [comment]
Interesting that it hangs! I think this might be related to the code that try to parse the Markdown component's import statement

**Comment by karlschwaier** [comment]
Thanks @Princesseuh, but it still hangs with prettier-plugin.astro 0.3.0.

Actually importing Markdown was not an issue. It just happens when importing Code oder Debug.

**Comment by Princesseuh** [comment]
I cannot reproduce with that version (and there's no code left related to those components)

If you're formatting in VS Code, make sure you restarted the editor after upgrading as it caches the plugin on first use!

**Comment by karlschwaier** [comment]
All good. Restart helped. It's fixed. 🙂 Thank you!
