### ISSUE TITLE
🐛 BUG: Does not work using global install of prettier-plugin-astro

### ISSUE THREAD

**Issue by jylin** [withastro/prettier-plugin-astro#258]
### Describe the Bug

I have "prettier-plugin-astro" installed only globally (via "npm install -g prettier-plugin-astro") instead of within the local package.

VSCode doesn't seem to format files if it's only installed globally. If I install "prettier-plugin-astro" locally into the current npm project, then it works.

### Steps to Reproduce

1. Install the plugin globally: `npm install -g prettier-plugin-astro`
2. Configure the VSCode plugin per the instructions
3. Try to format and it doesn't work

If you install the plugin locally, then formatting works.

**Comment by Princesseuh** [comment]
Hello, I can't find any information about this, but I'm not sure global plugins are supported by Prettier?

In general, Prettier does not recommend or officially support being installed globally as formatting can change between versions and the same goes for plugins.

You can see more information in their docs here: https://prettier.io/docs/en/install.html

**Comment by jylin** [comment]
Why not? If I run prettier cli it works fine with global plugins. I also use the java prettier plugin installed globally and it works fine in vscode.

**Comment by Princesseuh** [comment]
Since formatting can change between versions of the plugin, having it installed locally in your project ensure that every developer working on your project has the same version (and as such, the same formatting)

Nonetheless, if it works with other plugins, maybe we can get this to work!

I see some issues on the Prettier VS Code extension repo saying that globally installed plugins don't work, so it could be an issue on their end. I know they consume plugins fairly differently from the Prettier CLI

**Comment by antonyfaris** [comment]
@jylin you can use `prettier --write --plugin-search-dir=[PATH_TO_NODEJS] .`
For example for windows it will be `prettier --write --plugin-search-dir='C:\Program Files\nodejs' .`

**Comment by jylin** [comment]
It works fine if I just use prettier cli without any parameters. I assume prettier searches for plugins in the default global path too.

Actually, realizing now maybe this is not a problem with the prettier-astro plugin but instead something about the prettier vscode plugin.

**Comment by jylin** [comment]
Ended up resolving this by setting this in vscode: `"prettier.prettierPath": "/opt/homebrew/lib/node_modules/prettier"`
You actually don't even need to set ` "prettier.documentSelectors": ["**/*.astro"]` anymore after activating the above setting.
