### ISSUE TITLE
🐛 BUG: Added unnecessary break in `span` tag with expression

### ISSUE THREAD

**Issue by kagankan** [withastro/prettier-plugin-astro#278]
## Input

```astro
<span class="class"
  >{['long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'expression'].join('')
}</span>
```

## Output

```astro
<span class="class"
  >{['long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'long', 'expression'].join('')}
</span>
```

line break was inserted after expression.
so I got unnecessary space.
(line break in span tag is treated as space.)

## Notes

- I'm using prettier-plugin-astro via astro-vscode v0.24.4.
- my `printWidth` setting is `120`.

### Steps to Reproduce

See `Describe the Bug`

**Comment by kylemh** [comment]
This ends up hurting pretty hard with anybody using utility CSS (like Tailwind, for example)
