### ISSUE TITLE
🐛 BUG: Prettier-ignore comment doesn't work with astro files

### ISSUE THREAD

**Issue by zellwk** [withastro/prettier-plugin-astro#289]
### Describe the Bug

The `<!-- prettier-ignore -->` comment doesn't work in `.astro` files. Prettier continues to format the content. 

![Kapture 2022-10-01 at 18 45 59](https://user-images.githubusercontent.com/3607637/193406237-7713cd36-dad9-443b-9827-8fd68c77b714.gif)

But this same code works in a normal HTML file. Prettier respects the comment. 

### Steps to Reproduce

1. `npm init astro`using empty project
2. Put the following code inside the `index.astro` file.
```
<!-- prettier-ignore -->
  <div class="content-block">
      Paragraph 

      Paragraph

      ## Header 

      Paragraph
  </div>
```
3. Format the document.

**Comment by Princesseuh** [comment]
This is blocked by https://github.com/withastro/compiler/issues/575 at the moment, unfortunately
