### ISSUE TITLE
🐛 BUG: Fragments become self-closing tags

### ISSUE THREAD

**Issue by LedaThemis** [withastro/prettier-plugin-astro#290]
### Describe the Bug

Formatting a fragment that contains JSX causes that fragment to become a self-closing tag

Example:
```astro
<>
  {
    <div>Value</div>
  }
</>

```

Becomes
```astro
< />{(<div>Value</div>)}
```

After writing this, I realised that a fragment isn't neccessary at the root of a component.
Not sure if this issue is applicable anywhere else.

### Steps to Reproduce

1. `pnpm create astro` using template Empty project
2. Setup `prettier-plugin-astro`
3. Add the following in `src/components/Error.astro`
```astro
<>
  {
    <div>Value</div>
  }
</>
```
4. Add `Error.astro` in body of `index.astro`
5. Add the following script to `package.json`
```json
"format": "prettier -w --plugin-search-dir=. ."
```
6. Run `pnpm format`
7. You should see `src/components/Error.astro` as:
```astro
< />{(<div>Value</div>)}
```
8. Which would make the compiler display the following error:
```bash
Error: Uh oh, the Astro compiler encountered an unrecoverable error!
```

**Comment by Princesseuh** [comment]
Hello, thank you for reporting this issue!

This seems to come from a bug in the Astro compiler, the parsed AST doesn't seems to properly see the ending of the fragment, so Prettier ends up formatting it wrongly

```astro
<>{<div>Value</div>}</>
```
results in
```js
{
  type: 'root',
  children: [
    {
      type: 'fragment',
      name: '',
      attributes: [],
      children: [],
      position: [Object]
    },
    { type: 'expression', children: [Array], position: [Object] },
    { type: 'text', value: '\n', position: [Object] }
  ]
}
```
