### ISSUE TITLE
🐛 BUG: Style tags are moved inside html tag when it exists

### ISSUE THREAD

**Issue by Princesseuh** [withastro/prettier-plugin-astro#295]
### Describe the Bug

Followup to https://github.com/withastro/prettier-plugin-astro/issues/260, the compiler upgrade fixed it moving inside the `body`, but it now moves inside the `html`. That's still progress!

```html
<html>
  <head>

  </head>
  <body>

  </body>
</html>

<style>

</style>
```

becomes

```html
<html>
  <head> </head>
  <body> </body>

  <style></style>
</html>
```

### Steps to Reproduce

See description

**Comment by mrienstra** [comment]
One of the tests added in https://github.com/withastro/compiler/pull/541 (the PR that closed https://github.com/withastro/compiler/issues/318, "BUG: [AST] style tag is moved inside the body tag") is [internal/printer/printer_test.go#L2545-L2549](https://github.com/withastro/compiler/blob/4b68670/internal/printer/printer_test.go#L2545-L2549):

```
{
  name:   "style after html",
  source: `<html><body><h1>Hello world!</h1></body></html><style></style>`,
  want:   []ASTNode{{Type: "element", Name: "html", Children: []ASTNode{{Type: "element", Name: "body", Children: []ASTNode{{Type: "element", Name: "h1", Children: []ASTNode{{Type: "text", Value: "Hello world!"}}}}}, {Type: "element", Name: "style"}}}},
},
```

... So looks like this is a `withastro/compiler` issue. I just opened https://github.com/withastro/compiler/issues/585.
