### ISSUE TITLE
🐛 BUG: Single quotes in HTML attributes are turned into double quotes even if it's invalid

### ISSUE THREAD

**Issue by MarcusOtter** [withastro/prettier-plugin-astro#299]
### Describe the Bug

Input, with default settings (no .prettierrc):
```astro
<Layout title='"Welcome to Astro."'>
```

Output after formatting (not valid)
```astro
<Layout title=""Welcome to Astro."">
```

### Steps to Reproduce

1. `npm init astro` using template Just the basics
2. Go to `pages/index.astro` and try making the title of the page to `"Welcome to Astro."` (see code example above)
3. Format the file with prettier
4. Error, the result is `<Layout title=""Welcome to Astro."">` which is not valid.

**Comment by MarcusOtter** [comment]
I expect it to work like the default settings of Prettier (IIRC):

> Example: `"I'm double quoted"` results in `"I'm double quoted"` and `"This \"example\" is single quoted"` results in `'This "example" is single quoted'`.

**Comment by MarcusOtter** [comment]
This workaround also does not work:

Input
```astro
<Layout title="&quot;Welcome to Astro.&quot;">
```

Output
```astro
<Layout title=""Welcome to Astro."">
```

**Comment by MarcusOtter** [comment]
Ah, I tried it again now. I can reproduce it still, but as soon as I restart VSCode it starts working as intended. Might be a VSCode bug. So my full steps to reproduce it:

0. Have both the Astro extension (v.0.28.1) and the Prettier extension (v9.9.0) installed in VSCode
1. `npm init astro` using template Just the basics
2. Run `npm i --save-dev prettier-plugin-astro prettier`
3. Go to `pages/index.astro` and try making the title of the page to `"Welcome to Astro."` (see code example above)
4. Format the file with prettier
5. Error, the result is `<Layout title=""Welcome to Astro."">` which is not valid.

To fix:
1. Restart VSCode
2. Now it works 😄

So maybe this bug is out of our hands? If so feel free to close :)

**Comment by liam-macann** [comment]
I'm getting this issue through both the Prettier CLI and Sublime Text plugin, so don't believe it's a VSCode bug.

Input: `{ terms.map((term) => <span class='after:content-["this"] after:mx-4'>{term}</span>) }` 
Output: `{ terms.map((term) => <span class="after:content-["this"] after:mx-4">{term}</span>) }`

with both `singleQuote` and `jsxSingleQuote` set to `true`.

**Comment by Princesseuh** [comment]
I still cannot reproduce this. It's possible that this has been fixed somehow by the Prettier 3 port and everything. Please re-open an issue (with a reproduction) if this still happens!
