### ISSUE TITLE
🐛 BUG: Prettier throws error when combining self-closing tags and `prettier-ignore`

### ISSUE THREAD

**Issue by crutchcorn** [withastro/prettier-plugin-astro#306]
### Describe the Bug

When using the following `.astro` file:

```
<!-- prettier-ignore -->
<li/>
```

And running `prettier -w .` on the codebase, we get the following error:

```
src\components\mailing-list\mailing-list-full.astro
[error] src\components\mailing-list\mailing-list-full.astro: TypeError: Cannot read properties of undefined (reading 'offset')
[error]     at Object.locEnd (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier-plugin-astro\dist\index.js:758:45)
[error]     at Object.print (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier-plugin-astro\dist\index.js:311:50)
[error]     at callPluginPrintFunction (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8420:26)
[error]     at mainPrintInternal (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8369:22)
[error]     at mainPrint (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8356:18)
[error]     at C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8211:27
[error]     at AstPath.each (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8203:11)
[error]     at AstPath.map (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8210:14)
[error]     at Object.print (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier-plugin-astro\dist\index.js:322:50)
[error]     at callPluginPrintFunction (C:\Users\crutchcorn\git\Unicorn\astro-unicorn\node_modules\prettier\index.js:8420:26)
```

This seems to be caused by a bug within Astro's compiler. 

Namely, we end up looking for a `position.end` here:

https://github.com/withastro/prettier-plugin-astro/blob/main/src/index.ts#L33

But we're never passed one by the Astro compiler for any self-closing tag.

We can validate this by running `--inspect-brk` over the prettier script:

```
node --inspect-brk .\node_modules\prettier\bin-prettier.js --write src\components\mailing-list\mailing-list-full.astro
```

![A Chrome debugger showing only the start position enabled](https://user-images.githubusercontent.com/9100169/201635421-c92e2f79-0de9-4735-ae98-ae2d8bbbfa9a.png)

I will be submitting a PR to the Astro compiler very shortly to solve this issue (with tests).

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Change a `.astro` file to include a self-closing tag that's `prettier-ignore`d
3. Run `prettier -w .` with the `prettier-plugin-astro` plugin enabled
5. Error! See the error described as above

**Comment by Princesseuh** [comment]
Just a little update as to why this hasn't been closed and the update released despite a fix having been contributed:

While the fix works in fixing the crash, the returned position is off, so formatting with it unfortunately leads to content being cut off. Since this could corrupt the user's files, we'd rather it fails to format completely for now

We are currently investigating a fix in the compiler for this. Sorry for the inconvenience!
