### ISSUE TITLE
🐛 BUG: TypeScript in Astro `<script>`

### ISSUE THREAD

**Issue by DerYeger** [withastro/prettier-plugin-astro#315]
### Describe the Bug

Using `<script>` in Astro files enables TypeScript support.
However, using certain TypeScript features, like non-null assertions (e.g., `document.getById('#test')!`) results in an error (unexpected token).

### Steps to Reproduce

1. Use any Astro project.
2. In any Astro file, add a `<script>` that uses a TypeScript non-null assertion (e.g., `document.getById('#test')!`).
3. Run prettier with this plugin applied.
4. Error! The parser fails because of an unexpected token.

**Comment by Princesseuh** [comment]
Weird! We use directly the `typescript` parser inside script tags, which hopefully, would support Typescript features. I'll investigate, thank you for the report!

**Comment by Princesseuh** [comment]
Hello! This works correctly on my end. Do you have a more detailed reproduction? I tried with the following code:

```html
<script>
  const myElement = document.getElementById("hello");

  myElement!.hasAttribute;
</script>
```

**Comment by DerYeger** [comment]
Hi, thank you for looking into this!

[This branch](https://github.com/DerYeger/jan-mueller/tree/feature/projects) of my project has two files listed in the root dir's `.prettierignore`.
Removing them and running `pnpm lint` (this command runs `eslint`, which uses `eslint-plugin-prettier` to run `prettier`), will result in the following errors:

```
/Users/jan/workspace/jan-mueller/src/components/ThemeToggle.astro
  29:4  error  Parsing error: Unexpected token  prettier/prettier

/Users/jan/workspace/jan-mueller/src/components/project/Refunk.astro
  32:79  error  Parsing error: Missing semicolon  prettier/prettier
```

For example, [the script of the latter component](https://github.com/DerYeger/jan-mueller/blob/e2afa63e8a29d215bf87cdc93ff4a506b37b410d/src/components/project/Refunk.astro#L25) looks just fine too me.
Astro building/checking works just fine, so I'm not sure what's happening here.

**Comment by Princesseuh** [comment]
Hello again! 😄

Looked at your repo, I don't think this is an issue with the Prettier plugin. Trying to format those files with the plugin directly work just fine.

I suspect that the issue might be in the ESLint Astro plugin not supporting TypeScript inside script tags

**Comment by DerYeger** [comment]
Oh, sorry for the report! I just tested plain prettier myself and it works indeed.
