### ISSUE TITLE
🐛 BUG: Incorrect syntax error between <a> tags within nested JSX conditional

### ISSUE THREAD

**Issue by jyasskin** [withastro/prettier-plugin-astro#322]
### Describe the Bug

I have prettier-plugin-astro 0.7.2 installed.

### Steps to Reproduce

1. Make testcase.astro:

```astro
---
---
  { recipe ? (
        <nav>
          {test ? (
            <a href="/">
            Edit
          </a>
          <a href="/" >
            Delete
          </a> ) : null}
        </nav>
    ) : (
      <p>No such recipe.</p>
    )
  }
```

1. Reformat:

```
$ pnpm prettier -c --plugin-search-dir=. testcase.astro
Checking formatting...
testcase.astro[error] testcase.astro: SyntaxError: Unexpected token (7:15)
[error]    5 |             <a href="/">
[error]    6 |             Edit
[error] >  7 |           </a><a href="/">
[error]      |               ^
[error]    8 |             Delete
[error]    9 |           </a> ) : null}
[error]   10 |         </nav>
```

**Comment by jyasskin** [comment]
Ah, sorry, wrapping the elements in `<></>` fixes this, which means it was me being confused by [Astro's occasional support for not wrapping series of elements](https://docs.astro.build/en/core-concepts/astro-components/#fragments--multiple-elements).

**Comment by jasikpark** [comment]
Could come up with a better error for this case though... Is there a way to detect "this is mutliple elements that should be wrapped with a fragment"?
