### ISSUE TITLE
🐛 BUG: Parsing error: 'return' outside of function.

### ISSUE THREAD

**Issue by jsun969** [withastro/prettier-plugin-astro#326]
### Describe the Bug

when I write this in astro

```ts
if (!post) {
  return Astro.redirect('/404');
}
```

Prettier give me an error that I cannot format (eslint just for showing prettier's error):
![image](https://user-images.githubusercontent.com/29330847/216609887-5542033e-5b2c-4ce9-820b-7efc1c9eb8a5.png)

### Steps to Reproduce

https://github.com/jsun969/jsundotlol/blob/c901168568b93fd5e7038e1699948bb288869287/src/pages/blog/%5Bslug%5D.astro#L10-L13

**Comment by Princesseuh** [comment]
Hello, this error is coming from ESLint, not Prettier. The Prettier plugin is able to format this snippet with no errors.

I suspect that this is a similar issue to https://github.com/withastro/prettier-plugin-astro/issues/315, where the ESLint plugin does not pass the correct information to the Prettier plugin, or something similar.

Please create an issue on the ESLint plugin: https://github.com/ota-meshi/eslint-plugin-astro

**Comment by jsun969** [comment]
I think it must be a prettier error. When I run `prettier --write`

![image](https://user-images.githubusercontent.com/29330847/216968853-f6f99f7d-9423-449a-850d-80ce8853c4eb.png)
![image](https://user-images.githubusercontent.com/29330847/216968896-c32039ce-799b-4530-9a4e-704aff383d4f.png)

**Comment by Princesseuh** [comment]
Hmm, weird, this successfully format for me 🤔 I'll

**Comment by Princesseuh** [comment]
Tried a bunch of things, including your link and I cannot reproduce, sorry

**Comment by jsun969** [comment]
> Tried a bunch of things, including your link and I cannot reproduce, sorry

Gosh.. Maybe it's just my problem. I feel guilty for wasting your time 😓

I'll close this issue. Contact you again after I find a solution. Thanks a lot!

**Comment by Princesseuh** [comment]
> I feel guilty for wasting your time 😓
No worries, I'm paid by the hour 😄

**Comment by FugiTech** [comment]
Sorry to re-open this but I was having the same issue. I've narrowed it down to an interaction between Astro and @trivago/prettier-plugin-sort-imports. It seems like there was an issue filed with prettier-plugin-sort-imports but no progress has been made https://github.com/trivago/prettier-plugin-sort-imports/issues/210

I don't know enough about Prettier to understand if this is an issue entirely in prettier-plugin-sort-imports or in an interaction with it and prettier-plugin-astro.

**Comment by jasikpark** [comment]
mind creating an https://astro.new reproduction?

**Comment by FugiTech** [comment]
https://stackblitz.com/edit/github-pjbsr1?file=src/pages/index.astro

This is based on the "Just the basics" template. All I've done is run `npm add prettier prettier-plugin-astro @trivago/prettier-plugin-sort-imports`, added a basic `.prettierrc.cjs` that loads the two plugins, and added `if (false) { return Astro.redirect('/404') }` to `src/pages/index.astro`

If you run `npx prettier --write src/pages/index.astro` you'll see the "return outside of function" error. If you comment out the `return` line then it'll run as expected. Likewise if you leave the return uncommented but remove the `@trivago/prettier-plugin-sort-imports` plugin then prettier will run as expected.

**Comment by jsun969** [comment]
> https://stackblitz.com/edit/github-pjbsr1?file=src/pages/index.astro
> 
> This is based on the "Just the basics" template. All I've done is run `npm add prettier prettier-plugin-astro @trivago/prettier-plugin-sort-imports`, added a basic `.prettierrc.cjs` that loads the two plugins, and added `if (false) { return Astro.redirect('/404') }` to `src/pages/index.astro`
> 
> If you run `npx prettier --write src/pages/index.astro` you'll see the "return outside of function" error. If you comment out the `return` line then it'll run as expected. Likewise if you leave the return uncommented but remove the `@trivago/prettier-plugin-sort-imports` plugin then prettier will run as expected.

Awesome! Thx a lot!

**Comment by FugiTech** [comment]
If Astro wants to deprecate `return Astro.redirect(...)` and move to `throw Astro.redirect(...)` then I see no problem with that. 

Otherwise it seems like `src/printer/embed.ts` already has hacks in place for expressions in the html template, so maybe some more hacks could be added for the frontmatter? Might also require changes to the astro compiler as it looks like all of the frontmatter is stored as an individual string.
