### ISSUE TITLE
🐛 BUG: Custom Astro component Classes are not getting sorted

### ISSUE THREAD

**Issue by ni554n** [withastro/prettier-plugin-astro#333]
### Describe the Bug

Classes on default elements are getting sorted correctly whereas custom ones aren't. 
I have both `prettier-plugin-astro` and `prettier-plugin-tailwindcss` plugins installed. But I'm not sure which plugin is causing this issue.

### Steps to Reproduce

1. https://stackblitz.com/edit/node-lf1jgc?file=package.json,src%2Fpages%2Findex.astro,src%2Fcomponents%2FCustom.astro
2. Run `npm run format`
3. Check the classes order in `src/pages/index.astro` file

**Comment by Princesseuh** [comment]
Hello! Thank you for reporting this issue. It would be better suited in the Tailwind CSS Prettier plugin repo, however, as the issue is ultimately on their end
