### ISSUE TITLE
🐛 BUG: `*.astro`files not being formatted on guide setup

### ISSUE THREAD

**Issue by doganalper** [withastro/prettier-plugin-astro#334]
### Describe the Bug

I have setup prettier according to repo installation part but it looks like astro files does not being formatted.
![image](https://user-images.githubusercontent.com/48688801/226138075-3186ed04-1df8-43f0-a0ec-9837dfecf40c.png)

### Steps to Reproduce
Create new Astro project using cli and after that add prettier and prettier-plugin-astro packages according to installation of this repository.

**Comment by doganalper** [comment]
So running prettier like `prettier -w --plugin-search-dir=. .` works but on documentation it is recommended to use this way when using with pnpm but I'm using yarn.

**Comment by Princesseuh** [comment]
Are you using Yarn PnP by any chance?

**Comment by doganalper** [comment]
No I'm not using Yarn PnP.

**Comment by Princesseuh** [comment]
Hmm, weird. Maybe Yarn also has the same issue with plugin auto discovery that pnpm has. I'm thinking that we should probably instruct people to always explicitly put their plugins in their config to avoid this issue and ensure best compatibility with other plugins

**Comment by mdizo** [comment]
Just in case anyone's curious what it would look like:
```js
// pretterrc.cjs
module.exports = {
  pluginSearchDirs: [__dirname],
  plugins: [require.resolve('prettier-plugin-astro')],
  overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro'
      }
    }
  ]
}
```

**Comment by khanfluence** [comment]
I'm seeing `*.astro` files not be formatted after following the updated recommended config. This occurs with a new project (`npm create astro@latest`, Astro 2.8.3, Prettier 3.0.0, prettier-plugin-astro 0.11.0). Non-astro-type files are being formatted.

My preferred config location is `package.json`:
```
{
  "prettier": {
    "plugins": [
      "prettier-plugin-astro"
    ],
    "overrides": [
      {
        "files": "*.astro",
        "options": {
          "parser": "astro"
        }
      }
    ]
  }
}
```

I also removed my config in `package.json` and tried a JS file like the recommended config (module, though), but no dice:
```
export default {
  plugins: [import('prettier-plugin-astro')],
  overrides: [
    {
      files: "*.astro",
      options: {
        parser: "astro",
      },
    },
  ],
};
```

Am I doing something wrong?

**Comment by Princesseuh** [comment]
@khanfluence How are you formatting? CLI or VS Code (if so, using the Astro extension or using Prettier's)?

**Comment by khanfluence** [comment]
CLI  - `npx prettier  --write .`.

If it helps, when I try VS Code, either extension works fine with Astro files - no config required other than setting the default formatter. I'm going to use a package script to run formatting, so relying on VS Code isn't sufficient.

**Comment by Princesseuh** [comment]
Ah okay, there's currently a bug in Prettier where you have to manually specify the files for it to format files with custom extensions, see https://github.com/prettier/prettier/issues/15079

So if you do, for instance, the following:
```
npx prettier --write **/*.astro
```
it would work

**Comment by khanfluence** [comment]
Thank you! Prettier 3.0 has been a ride 😅
