### ISSUE TITLE
🐛 BUG: Formatter results in unwanted whitespace

### ISSUE THREAD

**Issue by thomastilkema** [withastro/prettier-plugin-astro#352]
### Describe the Bug

The extension automatically formats the following code:

```
<p>
  some text (<SomeComponent>content</SomeComponent>)
</p>
```

into:

```
<p>
  some text (<SomeComponent>
    content
  </SomeComponent>)
</p>
```

which results into the following text on screen (containing a space after `(` and one before `)`:

```
some text ( content )
```

### Steps to Reproduce

1. Create new Astro project: `npm create astro@latest`
2. Create a new component
3. Use it in a page or layout
4. See the result in your browser. I think the expected result would be to have spaces removed.

**Comment by xavdid** [comment]
I've been having trouble with getting `prettier` to actually ignore specific lines- my comments are moved around unexpectedly and I don't get consistent behavior out of the HTML or JS-style comment.

The best solution I've come up with in the meantime is to wrap child text in a JS string-

```tsx
<a href="...">
  {"longtextlongtextlongtextlongtextlongtextlongtextlongtextlongtext"}
</Layout>
```

**Comment by aczw** [comment]
I have the same issue. This is most noticeable if you add an underline to the text. If my custom `Link` component is formatted this way (and Prettier forces it to be this way):

```html
<Link
  href="https://google.com"
  newTab
>
  Google
</Link>
```

it looks this:

![image](https://github.com/withastro/prettier-plugin-astro/assets/79176651/d5f2fcfa-e16f-486a-9ba7-ecd6949c9999)

However, if I write it like this:

```html
<Link href="https://pennupgrade.com" newTab>Google</Link>
```

it now looks correct:

![image](https://github.com/withastro/prettier-plugin-astro/assets/79176651/4d5f3093-caee-4b40-a8dd-a2f244d1fb01)

Notice the lack of whitespace after "Google" and before the arrow. However, Prettier keeps forcing the beginning and end tags on newlines, causing the whitespace to appear. I can send more examples if needed.

**Comment by kdmcguire** [comment]
Also seeing this when creating a list of links. The elements are split onto different lines if the text is too long, resulting in some list items starting with empty space.

```
<li><a href="https://www.example.com" class="some-class">example.com</a></li>
<li><a href="https://www.example.com" class="some-class">example.com</a> (but some part of this line is longer)</li>
```

becomes

```
<li><a href="https://www.example.com" class="some-class">example.com</a></li>
<li>
    <a href="https://www.example.com" class="some-class">example.com</a> (but some part of this line is longer)
</li>
```

which comes out as:

- [example.com](https://www.example.com)
- ‎ [example.com](https://www.example.com) (but some part of this line is longer)

**Comment by theoephraim** [comment]
still having related issues with prettier running via the astro VSCode extension. Plus no way to disable prettier running :\
