### ISSUE TITLE
🐛 BUG: Prettier 3 not formatting .astro files

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [withastro/prettier-plugin-astro#358]
### Describe the Bug

I've started working on a new Astro site with the following in `package.json` (I used `npm i -D -E prettier@latest prettier-plugin-astro@latest`):

```
"devDependencies": {
  "prettier": "3.0.0",
  "prettier-plugin-astro": "0.11.0"
}
```

With this package versions, doing `npx prettier --write .` does not format any `.astro` file.

Also in WebStorm, doing Shift+Cmd+Option+P on a `.astro` file does not format it with Prettier as usual. Instead it says "Prettier: File index.astro has unsupported type".
 
<img width="367" alt="Captura de pantalla 2023-07-17 a les 21 33 59" src="https://github.com/withastro/prettier-plugin-astro/assets/4823860/e595c70b-9f42-4cac-babf-b03adf0f08e4">

Since I had another project where Prettier worked fine, I downgraded to the same versions (with `npm i -D -E prettier@2.8.8 prettier-plugin-astro@0.10.0`):

```
"devDependencies": {
  "prettier": "2.8.8",
  "prettier-plugin-astro": "0.10.0"
}
```

After downgrading then `.astro` files are picked and formatted correctly, and Shift+Cmd+Option+P works in WebStorm too.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. `npm i -D -E prettier@latest prettier-plugin-astro@latest`
3. Error: `npx prettier --write .` does not format .astro files

**Comment by Princesseuh** [comment]
This is caused by a bug in Prettier: https://github.com/prettier/prettier/issues/15079. At the moment, you need to manually specify `**/*.astro` in the CLI for it to work.

Not sure about the WebStorm part, but there's nothing we can do about it - better to bring it up to the JetBrains team.

**Comment by AlbertVilaCalvo** [comment]
Thanks. I'll just downgrade to 2.x for now which works perfect.

BTW doing `npx prettier --check **/*.astro` or `npx prettier --write **/*.astro` does not work, it errors:

```
[error] No parser could be inferred for file "/Users/.../src/layouts/MainLayout.astro".
[error] No parser could be inferred for file "/Users/.../src/pages/index.astro".
```

**Comment by Princesseuh** [comment]
I assume that much like https://github.com/withastro/prettier-plugin-astro/issues/360, you don't have the plugin in your Prettier config.

**Comment by AlbertVilaCalvo** [comment]
To make Prettier 3 work, I've added the "plugins" and "overrides" fields to my `.prettierrc.json` like this:

```json
{
  "semi": false,
  "singleQuote": true,
  "plugins": ["prettier-plugin-astro"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```

This makes Prettier work on WebStorm.

And for the CLI, instead of doing `npx prettier --write .` as usual, I have to do `npx prettier --write **/*.astro .`.
If I do `npx prettier --write .` it does not format `.astro` files, and if I do `npx prettier --write **/*.astro` it does not format other files different than `.astro` like `.json`.
