### ISSUE TITLE
🐛 BUG: prettier 3 adds single space after <br /> tag

### ISSUE THREAD

**Issue by mschoeffmann** [withastro/prettier-plugin-astro#359]
### Describe the Bug

Somehow, Prettier v3 adds a weird single space after a self-closing <br /> tag.
Since I did not find any documentation about this style, I assume this is a bug?

#### `src/pages/test300.astro`
```astro
<p>
  <b>test test test</b><br />
   test test test test test test test test test test test test test test<br />
   test test test test test test test test test test test test test test<br />
   test test test test test test test test test test test test test test test
  test test test test test test test test test test test test test<br />
   test test test test test test test test test test test test test test
</p>
```

#### `src/pages/test288.astro`
```astro
<p>
  <b>test test test</b><br />
  test test test test test test test test test test test test test test<br />
  test test test test test test test test test test test test test test<br />
  test test test test test test test test test test test test test test
  test test test test test test test test test test test test test test<br />
  test test test test test test test test test test test test test test
</p>
```

#### `.prettierrc.json`
```json
{
  "semi": false,
  "singleQuote": true,
  "plugins": ["prettier-plugin-astro"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```

### Steps to Reproduce

1. `pnpm create astro@latest prettier3-space-test` (empty, install deps, no ts, no git)
2. `pnpm install -D prettier prettier-plugin-astro`
3. create above mentioned files
4. `pnpm exec prettier --write src/pages/test288.astro`
5. see the newly appeared whitespaces in `test288.astro` like in `test300.astro`

**Comment by wackbyte** [comment]
I am also experiencing this

**Comment by wackbyte** [comment]
I am also experiencing this.

**Comment by stormynight9** [comment]
any updates?

**Comment by wackbyte** [comment]
Sorry for bumping this again, but have there been any updates?
