### ISSUE TITLE
🐛 BUG: Prettier 3: No parser could be inferred for astro files

### ISSUE THREAD

**Issue by EduardDopler** [withastro/prettier-plugin-astro#360]
### Describe the Bug

Formatting in VS Code with the Astro plugin and the prettier-plugin-astro doesn't work.

When triggering formatting it outputs:
```
["INFO" - 09:12:55] Formatting file:///Users/x/y/z.astro
["INFO" - 09:12:55] PrettierInstance:
{
  "modulePath": "/Users/dopler/x/y/node_modules/prettier/index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 43,
  "version": "3.0.0"
}
["INFO" - 09:12:55] Using ignore file (if present) at /Users/x/y/.prettierignore
["INFO" - 09:12:55] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 09:12:55] Parser not inferred, trying VS Code language.
["ERROR" - 09:12:55] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

I added the configs described in the readme to the VS code settings (i.e. `"prettier.documentSelectors": ["**/*.astro"]` and `"[astro]": { "editor.defaultFormatter": "esbenp.prettier-vscode" }`). I also tried combinations with and without these settings, to no avail.

Running prettier manually via `prettier --write **/*.astro` logs the same message:
```
[error] No parser could be inferred for file "/Users/x/y/z.astro".
```

This seems to be similar to https://github.com/withastro/prettier-plugin-astro/issues/358#issuecomment-1638866327.
I also tried to run it in Jetbrains IDEs and manually via npx command.

VS Code 1.80.1 on macOS 13.4.1
Node 18.16.1, npm 9.8.0
Astro 2.8.3, prettier-plugin-astro 0.11.0, prettier 3.0

### Steps to Reproduce

see above

**Comment by Princesseuh** [comment]
Could you share your Prettier config?

**Comment by EduardDopler** [comment]
> Could you share your Prettier config?

I use default settings. No .prettierrc or anything.
This is what I have (formatter-related) in my VS Code config:
```json
{
  "prettier.documentSelectors": ["**/*.astro"],
  "prettier.trailingComma": "all",
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[astro]": {
    "editor.defaultFormatter": "astro-build.astro-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

**Comment by Princesseuh** [comment]
You need to specify the plugin in your Prettier config, starting from Prettier 3 plugins are not autoloaded anymore. https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker

**Comment by EduardDopler** [comment]
Thank you @Princesseuh, that worked for both Jetbrains and VS Code! 🙌 
That means, we all need a .prettierrc file (or other configs) with the plugin explicitly listed?

**Comment by AlbertVilaCalvo** [comment]
To make Prettier 3 work, I've added the "plugins" and "overrides" fields to my `.prettierrc.json` like this:

```json
{
  "semi": false,
  "singleQuote": true,
  "plugins": ["prettier-plugin-astro"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```

This makes Prettier work on WebStorm.

And for the CLI, instead of doing `npx prettier --write .` as usual, I have to do `npx prettier --write **/*.astro .`.
If I do `npx prettier --write .` it does not format `.astro` files, and if I do `npx prettier --write **/*.astro` it does not format other files different than `.astro` like `.json`.

**Comment by ryanleichty** [comment]
If you're still getting the same errors after trying the solutions mentioned above, running the _Developer: Restart Extension Host_ command in VS Code solved the problem for me.

See https://flaviocopes.com/fixing-ts-issues-in-vs-code-astro/

**Comment by dpaulos6** [comment]
> To make Prettier 3 work, I've added the "plugins" and "overrides" fields to my `.prettierrc.json` like this:
> 
> ```json
> {
>   "semi": false,
>   "singleQuote": true,
>   "plugins": ["prettier-plugin-astro"],
>   "overrides": [
>     {
>       "files": "*.astro",
>       "options": {
>         "parser": "astro"
>       }
>     }
>   ]
> }
> ```
> 
> This makes Prettier work on WebStorm.
> 
> And for the CLI, instead of doing `npx prettier --write .` as usual, I have to do `npx prettier --write **/*.astro .`. If I do `npx prettier --write .` it does not format `.astro` files, and if I do `npx prettier --write **/*.astro` it does not format other files different than `.astro` like `.json`.

this solved it, thanks!

**Comment by ioson** [comment]
thanks, this fixed the formatting on save for .astro files in PhpStorm/WebStorm for me:
create `.prettierrc`
```
{
  "plugins": ["prettier-plugin-astro"]
}
```
