### ISSUE TITLE
🐛 BUG: My css and scss files are being formatted, but not my astro files

### ISSUE THREAD

**Issue by marcelluscaio** [withastro/prettier-plugin-astro#382]
### Describe the Bug

My astro files do not have format on save.

https://github.com/marcelluscaio/portfolioCaioCabral

### Steps to Reproduce

Clone the repository and try to edite the footer astro file

**Comment by jasikpark** [comment]
This is being tracked in https://github.com/withastro/prettier-plugin-astro/issues/373, it's an upstream issue w/ prettier 3.0, fixed in the unreleased 3.1.0
