### ISSUE TITLE
🐛 BUG: Prettier formatting silently fails when JSX conditionals return multiple elements

### ISSUE THREAD

**Issue by david-abell** [withastro/prettier-plugin-astro#387]
## Bug
Prettier formatting silently fails when JSX conditionals return multiple elements such as the below JSX conditional. Document will not format indentation or any other errors.

This is probably the same issue as referenced in #322 but that was closed without a fix.

```jsx
      {
        bool1 && bool2 && bool3 && (
            <div>Lorem ipsum dolor sit amet.</div>
                <div>Lorem ipsum dolor sit amet.</div>
                    <div>Lorem ipsum dolor sit amet.</div>
        )
      }
```

### Steps to Reproduce

1. `npm create astro@latest`
2. choose option: Include sample files
3. `npm i --save-dev prettier prettier-plugin-astro`
4. create recommended `.prettierrc.mjs` in docs

See this repo for a basic reproduction [https://github.com/david-abell/astro-prettier-jsx]( https://github.com/david-abell/astro-prettier-jsx)

## Expected outcome
Either formatting should work or an error should be shown on the problematic JSX expression.

## Actual outcome
Prettier does not fix formatting errors. 
Prettier shows no errors in document. 
Prettier output log shows the below:

```
["INFO" - 12:35:55 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 12:35:55 PM] Extension Version: 10.1.0.
["INFO" - 12:35:55 PM] Using config file at 'c:\Users\David Abell\Documents\Code\astro-prettier-jsx\.prettierrc.mjs'
```

## Workaround solution
The solution is easy if you know which part of the document is the problem and what to look for. Prettier starts working again after wrapping the JSX return value in a parent fragment fixes the problem.
```jsx
      {
        bool1 && bool2 && bool3 && (
            <>
              <div>Lorem ipsum dolor sit amet.</div>
              <div>Lorem ipsum dolor sit amet.</div>
              <div>Lorem ipsum dolor sit amet.</div>
            </>
        )
      }
```

**Comment by Princesseuh** [comment]
Hmm, that's weird. We have code for this, but maybe this is triggering a weird edge case. Thank you for creating an issue!

**Comment by nemanjam** [comment]
I still have this.

```
src/components/PostMeta.astro
[error] src/components/PostMeta.astro: SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (5:44)
[error]   3 |     <p aria-label="Post meta" class={cn('flex flex-row flex-wrap items-center gap-2', className)}>
[error]   4 |         {publishDate && (      
[error] > 5 |             <Icon name="mdi:access-time" /><time itemprop="datePublished" datetime={formatDateIso(publishDate)}>
[error]     |                                            ^
[error]   6 |               {formatDate(publishDate)}
[error]   7 |             </time>        
[error]   8 |         )}
```

```jsx
{
  shouldDisplay && (
    <p aria-label="Post meta" class={cn('flex flex-row flex-wrap items-center gap-2', className)}>
        {publishDate && (      
            <Icon name="mdi:access-time" />
            <time itemprop="datePublished" datetime={formatDateIso(publishDate)}>
              {formatDate(publishDate)}
            </time>        
        )}
```

**Comment by fvieira** [comment]
Hi @Princesseuh, just like @nemanjam I also keep seeing this error. I could open a new issue, but this one seems to fit so didn't want to polute with a new one.

Test case which fails to format with "Adjacent JSX elements must be wrapped in an enclosing tag." error, if I remove one of the inner divs it works:
```astro
<div>{true && (
    <div></div>
        <div></div>
)}</div>
```

Latest versions installed:
```
  "prettier": "^3.4.2",
  "prettier-plugin-astro": "^0.14.1",
```

.prettierrc.mjs
```
export default {
  plugins: ['prettier-plugin-astro'],
  overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro',
      },
    },
  ],
};
```

**Comment by fvieira** [comment]
Just saw issue #429 which was a better place to mention this, sorry. Will add an even simpler test case there.
