### ISSUE TITLE
🐛 BUG: Syntax Highlighting Lost and Incorrect Rendering When Condensing Code Blocks

### ISSUE THREAD

**Issue by jacobdalamb** [withastro/prettier-plugin-astro#404]
### Describe the Bug

Condenses the formatting into a more compact form.
Ex:
```
 <Fragment>
    ```sh
    npm run something
    ```
</Fragment>
```

![CleanShot 2024-01-26 at 07 53 54](https://github.com/withastro/prettier-plugin-astro/assets/44789941/83c2d0d0-9b5c-4480-8452-041082b6a61e)

to
```
   <Fragment>```sh npm run something```</Fragment>
```
![CleanShot 2024-01-26 at 07 54 25](https://github.com/withastro/prettier-plugin-astro/assets/44789941/af8cce06-afc0-4731-acdc-d1eb479550ba)

It loses syntax highlighting and is rendered incorrectly. 


### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by Princesseuh** [comment]
I'm not sure there's anything we can do about that, we cannot know that the content of your Fragment is supposed to not be formatted, wrapping your content in `pre` would fix the issue.

**Comment by jacobdalamb** [comment]
> I'm not sure there's anything we can do about that, we cannot know that the content of your Fragment is supposed to not be formatted, wrapping your content in `pre` would fix the issue.

I tried that and it didn't work.

**Comment by Princesseuh** [comment]
```ts
<Fragment>
  <pre>
    ```sh
      npm run something
    ```
  </pre>
</Fragment>
```
works for me, do you have a reproduction I can take a look at?

**Comment by jacobdalamb** [comment]
> ```astro
> <Fragment>
>   <pre>
>     ```sh
>       npm run something
>     ```
>   </pre>
> </Fragment>
> ```
> 
> works for me, do you have a reproduction I can take a look at?

https://stackblitz.com/edit/withastro-starlight-atagqz?file=src%2Fcontent%2Fdocs%2Finstallation.mdx run `npm run format`

**Comment by Princesseuh** [comment]
Ah, this is inside a MDX file. This plugin does not run inside MDX, it's only for Astro files. For issues with MDX, you'll need to report them to Prettier directly.
