### ISSUE TITLE
🐛 BUG: <script> formatting broken in files containing multi-byte characters

### ISSUE THREAD

**Issue by Garmelon** [withastro/prettier-plugin-astro#405]
### Describe the Bug

When trying to format an utf-8 encoded file that contains characters above code point `0x7f` *and* that contains a multi-line `<script>` tag, formatting fails with a `SyntaxError`. The error shows lines that differ from the lines in the file.

Note that a single-line script tag like `<script></script>` does not necessarily trigger the issue.

### Steps to Reproduce

1. Create the following astro file:
```astro
Hello wörld.

<script>
</script>
```

2. Try formatting it with `prettier` and `prettier-plugin-astro`
3. Observe the following error:
```
src/example.astro
[error] src/example.astro: SyntaxError: Unterminated regular expression. (3:2)
[error]   1 |
[error]   2 |
[error] > 3 | /script>
[error]     |  ^
[error]   4 |
```

Expected outcome: The file is formatted and looks like this:
```astro
Hello wörld.

<script></script>
```

**Comment by Garmelon** [comment]
A character seems to be replaced by a newline. Exactly which character depends on the amount of "extra bytes" in the file. With a single extra byte, the first character of `</script>` is affected. With two extra characters, the second character of `</script>` is affected, and so on.

We can confirm this using the `ö` and `€` characters. In utf-8, `ö` is two bytes large while `€` is three bytes large. Thus, a file containing `€` (2 extra bytes) and a file containing `öö` (2 extra bytes) should result in the same error message, and they do:

```astro
€
<script>
</script>
```

```astro
öö
<script>
</script>
```

```
[error] src/example.astro: SyntaxError: Unterminated JSX contents. (3:8)
[error]   1 |
[error]   2 | <
[error] > 3 | script>
[error]     |        ^
[error]   4 |
```

Adding more characters moves the affected character along further:

```astro
ööööööö
<script>
</script>
```

```
[error] src/example.astro: SyntaxError: Unexpected token (2:2)
[error]   1 |
[error] > 2 | </scri
[error]     |  ^
[error]   3 | t>
[error]   4 |
```

If the script tag is not empty, its contents are similarly affected:

```astro
ööö
<script>
"hello"
"world"
</script>
```

```
[error] src/example.astro: SyntaxError: Unterminated string constant. (2:1)
[error]   1 |
[error] > 2 | "h
[error]     | ^
[error]   3 | "hello"
[error]   4 | "world"
[error]   5 | cript>
```

**Comment by Princesseuh** [comment]
Weird, not too sure where that comes from. Thank you for reporting this issue!

**Comment by Garmelon** [comment]
This appears to be the fault of the https://github.com/neokidev/prettier-plugin-astro-organize-imports plugin. Without it, everything formats correctly. Closing this issue in favor of https://github.com/neokidev/prettier-plugin-astro-organize-imports/issues/105.
