### ISSUE TITLE
🐛 BUG: Markdown component indentation broken 

### ISSUE THREAD

**Issue by innermatrix** [withastro/prettier-plugin-astro#41]
### Describe the Bug

Astro prettier plugin breaks markdown inside `Markdown` component when it's nested in another element

### Steps to Reproduce

* Install astro prettier plugin
* Open attached file
* Format document

* Expected: indentation preserved
* Seen: Second paragraph indented (which then results in `<pre>` markup)

[test.astro.zip](https://github.com/snowpackjs/prettier-plugin-astro/files/7385211/test.astro.zip)

Before format document:

```
---
---



<div>
  <Markdown>
    Test Test

    Test
  </Markdown>
</div>
```

After format document: 

```
---
---



<div>
  <Markdown>
    Test Test

        Test
  </Markdown>
</div>
```

**Comment by antonyfaris** [comment]
I have a fix for this in the work, currently waiting for other PRs to get reviewed.
