### ISSUE TITLE
🐛 BUG: prettier fails to find the plugin

### ISSUE THREAD

**Issue by foxoter** [withastro/prettier-plugin-astro#412]
### Describe the Bug

Prettier fails to find the plugin with the following message: 

`Cannot find package 'prettier-plugin-astro' imported from <project-path>/noop.js`.

And therefore does not format my `.astro` files.

My `package.json`:

```
{
...
"dependencies": {
    ...
    "astro": "^4.4.6",
  },
"devDependencies": {
  "prettier": "3.2.5",
  "prettier-plugin-astro": "^0.13.0"
}
}
```

My `.prettierrc` looks like this: 
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "plugins": ["prettier-plugin-astro"]
}
```

My VScode user `settings.json` does include the following:
```
"prettier.documentSelectors": ["**/*.astro"],
"[astro]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"editor.defaultFormatter": "esbenp.prettier-vscode"
```

I also tried converting my Prettier config file into `.mjs` format and applying `await import('prettier-plugin-astro')`.

### Steps to Reproduce

1. bootstrap the default astro project
2. install astro VS Code extension
3. install prettier and astro plugin
4. run `prettier --write .` or even `prettier --write . --plugin=prettier-plugin-astro`

Expected: my `.astro` files are formatted.

Result: `Cannot find package 'prettier-plugin-astro' imported from <project-path>/noop.js`

**Comment by simonsmith** [comment]
I've also tried downgrading this plugin and prettier several versions (Prettier as low as `3.0.0`) and still the same issue. Could this be an Astro 4 related bug?

**Comment by simonsmith** [comment]
I found a fix:

**.prettier.cjs**
```js
module.exports = {
  semi: false,
  singleQuote: true,
  bracketSpacing: false,
  plugins: [require.resolve('prettier-plugin-astro')],
  overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro',
      },
    },
  ],
}
```

**Comment by Princesseuh** [comment]
There is nothing we can do about this in the plugin itself, this is either a Prettier issue or a configuration one. We have a recommended configuration in the README for a reason.

**Comment by DigitalNaut** [comment]
The above did not work for me, but I did a `Reload Window` via the Command Palette on VSCode and it fixed the problem spontaneously. 🤷‍♂️
