### ISSUE TITLE
🐛 BUG: Components inside `<Markdown>` are deleted by formatting the document

### ISSUE THREAD

**Issue by innermatrix** [withastro/prettier-plugin-astro#42]
### Describe the Bug

Components inside `<Markdown>` are deleted by formatting the document

### Describe the Bug

Astro prettier plugin deletes components inside a `Markdown` component

### Steps to Reproduce

* Install astro prettier plugin
* Copy-and-paste below input into a new `.astro` file
* Format document

* Expected: Inner component remains
* Seen: Inner component deleted

Input document:

```
---
---



<div>
  <Markdown>
  <Fragment>test</Fragment>
  </Markdown>
</div>
```

After format document: 

```
---
---



<div>
  <Markdown></Markdown>
</div>
```

**Comment by antonyfaris** [comment]
I have a fix for this in the work, currently waiting for other PRs to get reviewed.
