### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by thasmo** [withastro/prettier-plugin-astro#424]
### Describe the Bug

Using `prettier` and `prettier-plugin-astro` HTML tags stay uppercase and are not rewritten to lowercase:

```html
<HTML lang="en">
	<HEAD>
		<meta charset="utf-8" />
		<link href="/favicon.svg" rel="icon" type="image/svg+xml" />
		<meta content="width=device-width" name="viewport" />
		<meta content={Astro.generator} name="generator" />
		<title>Astro</title>
	</HEAD>

	<body>
		<h1>Astro</h1>
	</body>
</HTML>
```

`HTML` and `HEAD` should be reformatted to `html` and `head` but for some reason they stay as is.

### Steps to Reproduce

Set up a basic Astro project with `prettier` and `prettier-plugin-astro`.

**Comment by Princesseuh** [comment]
In Astro there's unfortunately no good way to know if something is a component or an html tag, the only distinction is the uppercase starting letter. As such, I'd say that this is an expected difference with Prettier's HTML support.

You can see this in action [in this link](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMTg0LDIxMSwxNjgsMTAyLDIsMywxMTcsODIsMjAxLDc4LDIyNyw2NCwxNiwyNTMsMTQ5LDE2OCwxNzUsMywxODIsMTM0LDE5LDY2LDMzLDgyLDQsMjA0LDQ4LDE4LDM1LDE0MSwyMjYsMjA0LDExNCwyNDAsMTY1LDIxMCw5MywxMTgsOTAsMjExLDEzOSw4NSw5Myw3OCw4OCwxOTYsMTkxLDgzLDEwOSwyMjcsMTYsMTI5LDU2LDExNywxODksMTcwLDI0NywxMDYsMjM3LDM5LDE2NSwxMjMsMzQsMTIsMTI0LDIxLDEyNSwxMDMsMjksMjEwLDMxLDE2NCwxMDAsOTksODAsMjMsMjM0LDE3Miw1Niw0NywyMDYsMjEyLDEzNywyMTAsMjA5LDE2MCwxOTIsMjQ5LDIzNywyNTAsMjMxLDIyMSwyMDQsNjUsMTA0LDQ3LDEwNywxMzMsMTYxLDg2LDEzOSw1OCwyMTIsNjAsMTkxLDE4OSw4OSw5NCwxNSwxNTAsMjE2LDMwLDI1LDEwMiwxMjIsMTEsMTQ4LDE0NCwxMzMsMjEyLDExNSwxMTUsMTIyLDk0LDE3MSw4OSw1NywxOTcsMTU3LDEzLDI1NSwxMDMsOTEsMTk0LDcwLDEzMCwxMDEsMyw1OSwxNzEsOTksNDAsMjEwLDE3NCwyMSwxNCwxNjEsMTksMTAzLDExOCw4LDIyNCwxMzUsMTQsNTEsMjQyLDIwOCw5OCw0MSwyNDEsNDcsMjQ3LDIyMiwyOSwyMzEsMjUsMjM1LDE5NiwxOTIsMjEwLDE4MywyNDAsMjQ2LDIxNCwyNDAsMjQ2LDIxMCwxNjAsMjI4LDE5NSwyMTEsMSw4LDU3LDEyOCwyMDcsNTcsMTE4LDIyLDI0Nyw5MywzNiwyNTQsODQsMjU0LDE4MCw3Niw3NiwxNzcsMTA0LDQ5LDMyLDEsNzEsMTIyLDE1OCwxNDgsNywyMDcsMTc3LDE0OCw0NSw1OSw5MiwxMiwxNDYsMTIxLDU3LDEzMCw5NywxMSwyMjksMTgwLDEzNCwxMiw1NCwyMDksNjAsNzYsMTMwLDIzNywyMTUsMTM3LDQ1LDIxNCw3MiwxMjUsMTMsMTM5LDcwLDIyLDE4NiwxNDQsNSwyMzksMzUsMTUzLDE5MSw0LDkzLDEzNSw3MCw5Myw1MiwyMjQsMTgsMTU4LDQwLDYzLDQ2LDE4OSwyMDMsMTg3LDIwLDIwMiwyNDAsMjU0LDEzOCwyMDEsMjQyLDExMiwyNywxNjYsOTQsNTYsNzYsMTYsODIsMTksMjAxLDI1NSwxNDQsODEsNDAsMTI4LDI1MSwxODksMTg2LDE5LDE0MSwyMDgsMjcsMTg1LDEwMCwzMCw2NywyMDgsMjEsMTQ0LDQxLDMyLDE4MywzMiwyNTQsMzIsMTAwLDExMiwyNDYsMTcsMjA1LDE4Myw1NSwxMzQsMjQ4LDE1LDE1MywxNzAsMjE2LDE0Nyw3MCwxNSwyMjEsMTYxLDE0NSw2NywxMDQsMjQsMjI3LDE4NywxMzksMjcsMTEyLDc1LDEwNiwyMTEsNTksOTcsMjU0LDYyLDE2MCwyNDksMTYzLDEwOCwxMzMsMTY5LDExOSw5MiwyMzMsNDAsMjExLDg1LDQ2LDE5MCw0OSwyNDIsMTAxLDE3NCwyMjksMTgsMjEwLDEzNiwyNSw3MywxNDYsMTE1LDI4LDQ0LDE2MSw2NywyMDUsMTA0LDIxNCw4MywxNDYsNTMsMTA4LDE2NCwyMjIsMjQwLDE3LDE0MywxNjIsMjEzLDE5MSwyMDksMjM5LDEwOSwyMTAsMTk5LDE4OSwyMjAsMjIwLDExOSw3MiwyMTQsMjAzLDExNywxOTMsMTczLDQ4LDI0LDE2NCw3NCwxNDcsMjM3LDE2NiwyMTAsMjA3LDQ3LDI0MywxOSwxNTgsMTgwLDI0NCwyLDAsMF0%3D), where the AST believe `HTML`, `HEAD` etc. to be components.
