### ISSUE TITLE
💡 RFC: Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by jasikpark** [withastro/prettier-plugin-astro#53]
### Background & Motivation

I want it to be clear how to get setup contributing to the project, and a more thorough guide would be helpful, which would list:

- How to get setup building and testing
- How to write tests
- What the design goals of the formatting are (which is mostly to try to follow the prettier rationale)

### Possible solutions
Add `CONTRIBUTING.md` or `contributing.md` to the repo
### Alternatives considered
Just expand the section in the README
### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by antonyfaris** [comment]
I think we should have a readme like the [svelte](https://github.com/sveltejs/prettier-plugin-svelte) one, we could add the new Astro options and add a link to contributing.md.

**Comment by jasikpark** [comment]
That sounds like a good plan
