### ISSUE TITLE
💡 RFC: Prettier Options

### ISSUE THREAD

**Issue by antonyfaris** [withastro/prettier-plugin-astro#54]
### Background & Motivation

This is a list of all the options that are missing from the plugin. We should probably add support for some.

- [Range](https://prettier.io/docs/en/options.html#range)
- [Parser](https://prettier.io/docs/en/options.html#parser)
- [File Path](https://prettier.io/docs/en/options.html#file-path)
- [Require Pragma](https://prettier.io/docs/en/options.html#require-pragma)
- [Insert Pragma](https://prettier.io/docs/en/options.html#insert-pragma)
- [Embedded Language Formatting](https://prettier.io/docs/en/options.html#embedded-language-formatting)
- [End of Line](https://prettier.io/docs/en/options.html#end-of-line)
- [Trailing Comma (the 'all' option)](https://prettier.io/docs/en/options.html#trailing-commas)

### Possible solutions

This one I think should be supported. And it may already be supported but I was having problems testing it.

- [End of Line](https://prettier.io/docs/en/options.html#end-of-line)

These ones I'm gonna need feedback:

- [Range](https://prettier.io/docs/en/options.html#range)
- [Require Pragma](https://prettier.io/docs/en/options.html#require-pragma)
- [Insert Pragma](https://prettier.io/docs/en/options.html#insert-pragma)
- [Embedded Language Formatting](https://prettier.io/docs/en/options.html#embedded-language-formatting)

These are the ones that I think shouldn't be supported:

- [Parser](https://prettier.io/docs/en/options.html#parser)
- [File Path](https://prettier.io/docs/en/options.html#file-path)
- [Trailing Comma (the 'all' option)](https://prettier.io/docs/en/options.html#trailing-commas)

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Closing since this is not as relevant anymore. If there's any settings that are not respected, please open individual issues.
