### ISSUE TITLE
🐛 BUG: Expression inside markdown files and the Astro markdown component

### ISSUE THREAD

**Issue by antonyfaris** [withastro/prettier-plugin-astro#61]
### Describe the Bug

Currently, the plugin doesn't format markdown files we leave that to Prettier. But we need to take over the default markdown formatter from Prettier to be able to format expressions.

### Steps to Reproduce

Input:

```md
{frontmatter.value * 2} 
```

Output:

```md
{frontmatter.value \* 2} 
```

Expected output:

```md
{frontmatter.value * 2} 
```

**Comment by antonyfaris** [comment]
This will also happen inside the Astro markdown component.

**Comment by Princesseuh** [comment]
Since Astro flavored Markdown is now legacy, this is not necessary anymore
