### ISSUE TITLE
🐛 BUG: Header and Footer components are being lowercased

### ISSUE THREAD

**Issue by JuanM04** [withastro/prettier-plugin-astro#75]
### Describe the Bug

When I use a component `<Header />` or `<Footer />` (maybe happens with more components, but I'm not aware of that) they are converted to `<header />` and `<footer />` HTML elements when they shouldn't

### Steps to Reproduce

1. `npm init astro` using template `minimal`
2. Install `prettier` and `prettier-plugin-astro`
3. Create two components: `Header.astro` and `Footer.astro`
4. Replace your `index.astro` with this:
```astro
---
import Header from "../components/Header.astro";
import Footer from "../components/Footer.astro";
---

<html lang="en">
  <body>
    <Header />

    <h1>Welcome to <a href="https://astro.build/">Astro</a></h1>

    <Footer />
  </body>
</html>
```
5. Run `prettier -w .` (maybe you'll have to run it twice)
6. You'll see the components `<Header />` to be `<header />` (and the same with Footer)

**Comment by antonyfaris** [comment]
I think I know what is causing this, I will take look. Thanks for the report.

**Comment by talionar** [comment]
Also the same with Nav and Button. I guess with all native HTML tags clashing with component names
