### ISSUE TITLE
🐛 BUG: Markup inside component inside Markdown incorrectly indented

### ISSUE THREAD

**Issue by innermatrix** [withastro/prettier-plugin-astro#76]
### Describe the Bug

Input

```
<Markdown>
  <Fragment>
  <div>
  <div/>
  </div>
  </Fragment>
</Markdown>
```

Output: unchanged

Expected

```
<Markdown>
  <Fragment>
    <div>
      <div/>
    </div>
  </Fragment>
</Markdown>
```

### Steps to Reproduce

See above. Plugin 0.0.11.

**Comment by Princesseuh** [comment]
[The Markdown component will be deprecated soon](https://github.com/withastro/rfcs/blob/main/proposals/0000-deprecate-markdown-component.md). As such, issues related to it won't be fixed, sorry
