### ISSUE TITLE
🐛 BUG: Footnote inside markdown inside expression breaks after formatting with 0.0.11

### ISSUE THREAD

**Issue by innermatrix** [withastro/prettier-plugin-astro#77]
### Describe the Bug

Input:

```
{foo ?? (
  <Markdown>
    Test. [^1] 
    
    [^1]: Test.
  </Markdown>
)}
```

Output:

```
{foo ?? <Markdown>Test. [^1] [^1]: Test.</Markdown>}
```

Compare with 

Input

```
<Markdown>
  Test. [^1]

  [^1]: Test.
</Markdown>
```

Output: unchanged.

The issue is that correct rendering of a footnote requires it to be on a separate line, so this reformatting breaks the footnote. 

### Steps to Reproduce

See above

**Comment by Princesseuh** [comment]
[The Markdown component will be deprecated soon](https://github.com/withastro/rfcs/blob/main/proposals/0000-deprecate-markdown-component.md). As such, issues related to it won't be fixed, sorry
