### ISSUE TITLE
🐛 BUG: No parser could be inferred for file: Author.astro when using pnpm

### ISSUE THREAD

**Issue by rburgst** [withastro/prettier-plugin-astro#97]
### Describe the Bug

When trying to format / check an `.astro` file, it does not seem to be able to recognize the formatter when using pnpm.

It does work with `yarn`.

### Steps to Reproduce

1. `npm init astro` using template blog
2. install dependencies with `pnpm install`
3. add the plugin `pnpm i --save-dev prettier-plugin-astro`
4. try to prettier an astro file `pnpm prettier src/components/Author.astro -c`

```
Checking formatting...
src/components/Author.astro[error] No parser could be inferred for file: src/components/Author.astro
All matched files use Prettier code style!
```

**Comment by rburgst** [comment]
note that when I am using yarn 2, I get 

```
yarn format
Usage Error: Couldn't find a script named "prettier".
```

**Comment by antonyfaris** [comment]
This is a bug from Prettier itself. See https://github.com/prettier/prettier/issues/8056

**Comment by jimmy-guzman** [comment]
I was able to get it to work based on this [comment](https://github.com/sveltejs/prettier-plugin-svelte/issues/155#issuecomment-831166730)

To get the prettier cli to behave with pnpm, you can do the following: 

* pass `--plugin-search-dir=.`  to the prettier cli
* add `plugins: [require.resolve('prettier-plugin-astro')]` to the `.prettierrc.js`

Also, to get it to work with vscode, you must also do the following:
* add `"prettier.documentSelectors": ["**/*.astro"]` to the VSCode `settings.json`
* add the astro parser to the `.prettierrc.json`, i.e.
```js
  overrides: [
    {
      files: '**/*.astro',
      options: { parser: 'astro' },
    },
  ],
```

**Comment by ekafyi** [comment]
I use pnpm workspace (same structure as the official astro.new "component" template) and this is the only VSCode setup that works for me:

On your project root, add `.vscode/whatever.code-workspace` with the following content (`whatever` can be any name)

```json
{
  "folders": [
    {
      "path": ".."
    }
  ],
  "settings": {
    "prettier.documentSelectors": [
      "**/*.astro"
    ],
    "[astro]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode",
      "editor.formatOnSave": true
    }
  }
}
```

`prettier.documentSelectors` did NOT work in `settings.json`.

The prettier config (`.prettierrc`) and CLI setup is the same as @jimmy-guzman 's post above.

**Comment by djmtype** [comment]
@ekafyi I still couldn't my .astro files to format on save using VS workspace. Would you mind sharing your repo or codesandbox? 

The only thing that worked was running `pnpm run format` which runs "format": "yarn prettier -w . --plugin-search-dir=." However, that formats every single file in the project – not what I want.

**Comment by ekafyi** [comment]
@djmtype The code is in a private repo, going to make a simple reproduction when i have the time. Yes, I use `esbenp.prettier-vscode` extension.

In the meantime, if you want the `format` command to only format astro files, you can do this:

```diff
- "format": "yarn prettier -w . --plugin-search-dir=."
+ "format:astro": "yarn prettier -w src/components/*.astro --plugin-search-dir=."
```

Just curious — does it also not work when you paste these options to your global VSCode settings ("Preferences: Open Settings (JSON)")?

```
    "prettier.documentSelectors": [
      "**/*.astro"
    ],
    "[astro]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode",
      "editor.formatOnSave": true
    }
```

**Comment by djmtype** [comment]
> ```diff
> - "format": "yarn prettier -w . --plugin-search-dir=."
> + "format:astro": "yarn prettier -w src/components/*.astro --plugin-search-dir=."
> ```

Thanks for the tip!

**Comment by djmtype** [comment]
@ekafyi I haven't had any luck with pnpm in regards to getting my files to format on save when using global or workspace settings. pnpm will only work as a separate task.

npm works without issue. But, I'd rather not have duplicate modules on my machine.

**Comment by kissu** [comment]
This
```js
"prettier": {
  "documentSelectors": [
    "**/*.astro"
  ]
},
```
leads to `Unknown Configuration Setting` (IntelliSense) when hovered in the latest release of VScode, so we can probably forget this one.

Something like this `pnpm prettier -w src/pages/about.astro --plugin-search-dir=.` works perfectly fine at least. 👍🏻 

But of course, nothing from above gives a result. 😿 

This would be nice as a `Palette` + `Format Document` but godlike if available through an ESlint autorun or even via the [Astro extension](https://github.com/withastro/language-tools/issues/124).

**Comment by Princesseuh** [comment]
We unfortunately cannot fix the underlying issue ourselves, however can definitely document this much better. As such instructions on how to get this working with pnpm has been added to the plugin's README in the next version. 

Additionally, we're in the process of adding instructions inside the Astro docs too (https://github.com/withastro/docs/pull/831). Hopefully, that'll cover it much better!

**Comment by vuolter** [comment]
I encountered this error too in my last pnpm project and solved it by moving my prettier config to the file `package.json` this way:
```
{
    "name": "my-project",
    "type": "module",
    ...
    "prettier": {
        "astroAllowShorthand": true,
        "overrides": [
            {
                "files": "*.astro",
                "options": {
                    "parser": "astro"
                }
            }
        ],
        "pluginSearchDirs": [
            "."
        ],
        "plugins": [
            "prettier-plugin-astro"
        ]
    }
}
```

**Comment by jjaimealeman** [comment]
> - "format": "yarn prettier -w . --plugin-search-dir=."
> + "format:astro": "yarn prettier -w src/components/*.astro --plugin-search-dir=."

When I run `yarn format` it works fine.
Although `yarn format:astro` I get this error.

![image](https://github.com/withastro/prettier-plugin-astro/assets/1428292/78d176c3-8313-4089-b95a-86992b352715)

My `settings.json` has:
```
    "[astro]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    "prettier.documentSelectors": [
        "**/*.astro"
    ],
```

**Comment by Princesseuh** [comment]
> > - "format": "yarn prettier -w . --plugin-search-dir=."
> > + "format:astro": "yarn prettier -w src/components/*.astro --plugin-search-dir=."
> 
> When I run `yarn format` it works fine.
> Although `yarn format:astro` I get this error.
> 
> ![image](https://github.com/withastro/prettier-plugin-astro/assets/1428292/78d176c3-8313-4089-b95a-86992b352715)
> 
> My `settings.json` has:
> ```
>     "[astro]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode",
>         "editor.formatOnSave": true
>     "prettier.documentSelectors": [
>         "**/*.astro"
>     ],
> ```
> 

Do you have the Prettier plugin in your Prettier config?

**Comment by jjaimealeman** [comment]
> Do you have the Prettier plugin in your Prettier config? Prettier 3 deprecated plugin auto load and now plugins need to be manually specified in your config.

This is the contents of my `prettier.config.js` 🤔 

```
// prettier.config.js
module.exports = {
  tailwindConfig: "./tailwind.config.cjs",
  plugins: [
    require("prettier-plugin-tailwindcss"),
    require.resolve("prettier-plugin-astro"),
  ],
  overrides: [
    {
      files: ["**/*.astro"],
      options: {
        parser: "astro",
      },
    },
  ],
};
```

**Comment by Princesseuh** [comment]
Hmm, it seems like the plugin doesn't get loaded. Perhaps try replacing `require.resolve("prettier-plugin-astro")` with just `"prettier-plugin-astro"`
